Implement backend for patch validation
open-sirus/launcher pull request #1
Opened 2020-11-11 01:01 UTC by avengerweb

2020-11-11 17:58 UTC, avengerweb commented on tests/unit/store/modules/app.spec.ts
>    it.skip('cleanup incomplete downloads after restart', async () => {
Ты их добавил ))

2020-11-14 09:11 UTC, bondiano requested changes

2020-11-14 09:11 UTC, bondiano commented on src/background/ClientActions.ts
>  import LauncherListener from '@/events/LauncherListener'
Из всего, кроме vue файлов давай делать именованные экспорты https://medium.com/@etherealm/named-export-vs-default-export-in-es6-affb483a0910

2020-12-08 00:12 UTC, avengerweb commented on src/services/FileManageService.ts
> +  files: Array<LauncherFile> = []
я тоже так думал, но это не удобно получилось, придется гонять ее через ивенты включая весь стейт, тут вылезает куча других проблем, например мы не должны запускать валидацию если она уже в процессе или в загрузка в процессе. Плюс это должен быть флоу, проверили, загрузили, проверили. Эти стейты все равно где то придется хранить, он будет часто изменятся (например прогресс проверки файла или загрузки), хранить его в vuex в рендере не значит гонять его туда сюда, а вуекса в бекграунде у нас увы нет.

2020-12-08 07:21 UTC, merged