Tray implementaion for app
open-sirus/launcher pull request #2
Opened 2020-11-17 10:13 UTC by MikhailShibaev

2020-11-17 10:19 UTC, bondiano requested changes

2020-11-17 10:19 UTC, bondiano commented on src/background.ts
> +  winId = win.id
зачем?

2020-11-17 10:19 UTC, bondiano commented on src/events/LauncherEvent.ts
> +  runGame: boolean
название

2020-11-19 12:38 UTC, bondiano commented on src/background/tray/contextMenu.ts
> +export const reBuildMenu = (eventData: IEventData, menu: Menu, tray: Tray) => {
build просто должна быть идемпотентной

2020-11-19 13:25 UTC, MikhailShibaev commented on src/background/tray/contextMenu.ts
> +export const reBuildMenu = (eventData: IEventData, menu: Menu, tray: Tray) => {
Эм. Как это? reBuildMenu же прям говорит о том что она будет перестраивать меню.

2020-11-22 07:50 UTC, bondiano commented on src/background.ts
> +export const isDevelopment = process.env.NODE_ENV !== 'production'
из этого модуля точно ничего не надо экспортровать

2020-11-22 07:52 UTC, bondiano commented on src/background/tray/contextMenu.ts
> +export const reBuildMenu = (eventData: IEventData, menu: Menu, tray: Tray) => {
при одних входящих данных она всегда строит одно и тоже меню, сколько не вызывай. Потому это можно и просто buildMenu назвать

2020-11-22 07:53 UTC, bondiano commented on src/background/tray/contextMenu.ts
> +export const buildMenuFromTemplate = (
она вроде внутренняя и нигде не экспортируется, да и `Menu.buildFromTemplate` можно по месту испольщовать, не понимаю смысл обвязки

2020-11-22 07:54 UTC, bondiano commented on src/background/tray/contextMenu.ts
> +  buildMenuFromTemplate([
а вот массив внутри можно вынести и получать его - тут мы строим представление, также описать тип возвращаемый из функции, отвечающей за генерациб меню

2020-11-22 07:55 UTC, bondiano commented on src/background/tray/helpers.ts
> +export const getMainWindowById = (winId: number): BrowserWindow => {
не понимаю смысл этой обвзяки, да еще и с обманывающим ожидание названием

2020-11-22 07:55 UTC, bondiano commented on src/background/tray/trayEventHandlers.ts
> +      id: '3',
давай idшечки всегда генерировать через `nanoid`

2020-11-22 08:39 UTC, MikhailShibaev commented on src/background.ts
> +export const isDevelopment = process.env.NODE_ENV !== 'production'
я думал вынести это в `constants.ts`

2020-11-22 08:40 UTC, MikhailShibaev commented on src/background/tray/contextMenu.ts
> +  buildMenuFromTemplate([
Зачем тип описывать? Возвращается `Menu` же

2020-11-23 08:18 UTC, MikhailShibaev commented on src/background/tray/contextMenu.ts
> +export const buildMenuFromTemplate = (
убрал

2020-11-23 08:18 UTC, MikhailShibaev commented on src/background/tray/helpers.ts
> +export const getMainWindowById = (winId: number): BrowserWindow => {
Солидарен, делал для красоты) убрал

2020-11-23 08:27 UTC, MikhailShibaev commented on src/background/tray/contextMenu.ts
> +  buildMenuFromTemplate([
в массиве используется `mainWindow` вынести не получится

2020-11-24 15:16 UTC, bondiano commented
Иконки под разные платформы

2020-11-24 15:16 UTC, bondiano commented on src/background/tray/index.ts
> +  const mainWindow = BrowserWindow.fromId(winId)
лушче сразу win передать, как он заиницилизирвался

2020-11-24 15:17 UTC, bondiano commented on src/background/tray/index.ts
> +  tray.setToolTip('Sirus launcher')
вынести хардкод

2020-11-24 15:18 UTC, bondiano commented on src/background/tray/index.ts
> +  const initialMenu = initialContextMenu(mainWindow)
```suggestion
  const initialMenu = initContextMenu(mainWindow)
```

2020-11-24 15:19 UTC, bondiano commented on src/background/tray/contextMenu.ts
> +      click: () => {},
не нужнл

2020-11-24 15:19 UTC, bondiano commented on src/background/tray/contextMenu.ts
> +      label: '',
лишнее

2020-11-24 15:20 UTC, bondiano commented on src/background/tray/types.ts
> +export enum menuComponentTypes {
`const emum`

2020-11-24 15:26 UTC, bondiano commented on src/background/tray/contextMenu.ts
> +}
отбивка

2020-11-24 15:26 UTC, bondiano commented on src/background/tray/contextMenu.ts
> +export const buildMenu = (eventData: IMenuItem, menu: Menu, tray: Tray) => {
```typescript
interface IMenu extends MenuItem {
  nodeType?: menuComponentTypes
}

export const buildMenu = (eventData: IMenuItem, menu: Menu, tray: Tray) => {
  const menuItem: IMenu = new MenuItem(eventData)

  const filteredMenuItems = (menu.items as IMenu[]).filter(
    (item) => item.nodeType !== menuItem.nodeType
  )
```

2020-11-24 15:27 UTC, bondiano commented on src/background/tray/contextMenu.ts
> +export const buildMenu = (eventData: IMenuItem, menu: Menu, tray: Tray) => {
и убрать `// @ts-ignore`

2020-11-24 15:27 UTC, bondiano commented on src/constants.ts
> +// tray
отбивочки перед новым блоком (поставь везде плез)

2020-11-24 15:30 UTC, bondiano commented on src/background/tray/index.ts
> +export const initTray = (winId: number): Tray => {
давай вынесем в отдельный файлик, а все экспорты из соседних файлов, что "публичный интерфейс модуля", заэкспортим тут

2020-11-24 15:32 UTC, bondiano commented
И юнит тесты

2020-11-25 11:07 UTC, MikhailShibaev commented on src/constants.ts
> +// tray
сделал

2020-11-25 11:15 UTC, MikhailShibaev commented on src/background/tray/contextMenu.ts
> +export const buildMenu = (eventData: IMenuItem, menu: Menu, tray: Tray) => {
Поправил

2020-11-25 11:15 UTC, MikhailShibaev commented on src/background/tray/contextMenu.ts
> +}
Сделал

2020-11-25 11:15 UTC, MikhailShibaev commented on src/background/tray/types.ts
> +export enum menuComponentTypes {
Сделал

2020-11-25 11:37 UTC, MikhailShibaev commented on src/background/tray/contextMenu.ts
> +      label: '',
Убрал

2020-11-25 11:38 UTC, MikhailShibaev commented on src/background/tray/contextMenu.ts
> +      click: () => {},
Тож убрал

2020-11-25 11:40 UTC, MikhailShibaev commented on src/background/tray/index.ts
> +  const initialMenu = initialContextMenu(mainWindow)
Поправил

2020-11-25 12:31 UTC, MikhailShibaev commented on src/background/tray/index.ts
> +  tray.setToolTip('Sirus launcher')
вынес

2020-11-25 12:31 UTC, MikhailShibaev commented on src/background/tray/index.ts
> +  const mainWindow = BrowserWindow.fromId(winId)
Сделал

2020-11-30 08:59 UTC, bondiano approved these changes

2020-11-30 08:59 UTC, merged